### PR TITLE
Fatal Error when WooCommerce is not installed

### LINKED ISSUE #549: Fatal Error when WooCommerce is not installed
Uncaught Error: Call to undefined function wc_help_tip() in /wp-content/plugins/my-plugin/packages/action-scheduler/classes/ActionScheduler_wcSystemStatus.php:101

### PR DESCRIPTION
**Pull request by crstauf**
Closes #549.

### CODE REVIEW

File: classes/ActionScheduler_wcSystemStatus.php [hunk 1]
```diff
@@ -94,12 +94,16 @@ protected function get_action_status_date( $status, $date_type = 'oldest' ) {
 	protected function get_template( $status_labels, $action_counts, $oldest_and_newest ) {
 		$as_version = ActionScheduler_Versions::instance()->latest_version();
 		$as_datastore = get_class( ActionScheduler_Store::instance() );
+
+		$tip = '';
+		if ( function_exists( 'wc_help_tip' ) )
```
Comment (rrennick) [inline classes/ActionScheduler_wcSystemStatus.php:99]: @crstauf Could you add braces to the `if` block?

**Review by rrennick — APPROVED** [review]
@crstauf Thanks for the fix.
